const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("desktop", {
  getInfo: () => ipcRenderer.invoke("desktop:get-info"),
  chooseWorkspace: () => ipcRenderer.invoke("desktop:choose-workspace"),
  importMedia: () => ipcRenderer.invoke("desktop:import-media"),
  searchAssets: (query) => ipcRenderer.invoke("desktop:search-assets", query),
  researchAccount: (input) => ipcRenderer.invoke("desktop:research-account", input),
  downloadResearchMedia: (input) => ipcRenderer.invoke("desktop:download-research-media", input),
  analyzeResearchMedia: (input) => ipcRenderer.invoke("desktop:analyze-research-media", input),
  quoteTopicRadar: (input) => ipcRenderer.invoke("desktop:quote-topic-radar", input),
  runTopicRadar: (quoteId) => ipcRenderer.invoke("desktop:run-topic-radar", quoteId),
  listTopicRadarReports: () => ipcRenderer.invoke("desktop:list-topic-radar-reports"),
  createCaptureWorkflow: (input) => ipcRenderer.invoke("desktop:create-capture-workflow", input),
  importTake: (shootTaskId) => ipcRenderer.invoke("desktop:import-take", shootTaskId),
  selectTake: (input) => ipcRenderer.invoke("desktop:select-take", input),
  proposeEdit: (projectId) => ipcRenderer.invoke("desktop:propose-edit", projectId),
  renderEdit: (input) => ipcRenderer.invoke("desktop:render-edit", input),
  exportExchange: (input) => ipcRenderer.invoke("desktop:export-exchange", input),
  createPublishPackage: (input) => ipcRenderer.invoke("desktop:create-publish-package", input),
  listPublications: () => ipcRenderer.invoke("desktop:list-publications"),
  recordMetrics: (input) => ipcRenderer.invoke("desktop:record-metrics", input),
  proposeReviewMemory: (input) => ipcRenderer.invoke("desktop:propose-review-memory", input),
  confirmReviewMemory: (proposalId) => ipcRenderer.invoke("desktop:confirm-review-memory", proposalId),
  openWorkspaceFile: (relativePath) => ipcRenderer.invoke("desktop:open-workspace-file", relativePath),
  openExternal: (url) => ipcRenderer.invoke("desktop:open-external", url),
});
